sudo: required
language: generic
services:
    - docker
before_install:
    - docker build -t feistyfugu/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true feistyfugu/docker-react npm run test